// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdelumjintfylehvbxpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkZWx1bWppbnRmeWxlaHZieHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDI4OTMsImV4cCI6MjA2NzgxODg5M30.4t_4T6ZCqrLwVjrIk_gnUQuTqLLjlMct8Dqu3WCqvEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});